### ISSUE TITLE
Bấm vào view detail thì mất bảng tính năng

### ISSUE THREAD

**Issue by tanminh** [daltonnyx/homeclick#20]
<img width="960" alt="screenshot 2017-10-30 14 17 46" src="https://user-images.githubusercontent.com/33215297/32158815-284fb2b6-bd7d-11e7-89d4-d0749e3d0765.png">

**Comment by tanminh** [comment]
Ý là cái này nó không hiện bảng view detail ra, chứ nó hiện ra cái detail thì không cần bảng tính năng làm gì

**Comment by daltonnyx** [comment]
À rồi hiểu :smiley:
