### ISSUE TITLE
Có thể xuất hình với template có logo của Homeclick.vn và tên của layout được đang thực hiện

### ISSUE THREAD

**Issue by tanminh** [daltonnyx/homeclick#24]
![screenshot 2017-10-31 21 13 36](https://user-images.githubusercontent.com/33215297/32228644-64100116-be81-11e7-84d0-5b8460d5adfc.png)

**Comment by tanminh** [comment]
Nó sẽ như thế này,
[31.10.2017 Export.pdf](https://github.com/daltonnyx/homeclick/files/1433465/31.10.2017.Export.pdf)

**Comment by daltonnyx** [comment]
😭

**Comment by daltonnyx** [comment]
Finished 
[asdas.pdf](https://github.com/daltonnyx/homeclick/files/1634166/asdas.pdf)

**Comment by tanminh** [comment]
Xuất theo định này như file đính kèm.

**Comment by tanminh** [comment]
Hãy xem đây
![page 1](https://user-images.githubusercontent.com/33215297/35332467-a1a496be-013d-11e8-9472-585126be67d2.jpg)
![page 2](https://user-images.githubusercontent.com/33215297/35332468-a1d9da68-013d-11e8-8a8e-ea2a54c2e7d6.jpg)
![page 3](https://user-images.githubusercontent.com/33215297/35332469-a20dec54-013d-11e8-926d-53cd5556da07.jpg)
