### ISSUE TITLE
Bấm refresh thì map sàn vẫn còn

### ISSUE THREAD

**Issue by tanminh** [daltonnyx/homeclick#28]

**Comment by tanminh** [comment]
<img width="960" alt="screenshot 2017-10-31 21 39 07" src="https://user-images.githubusercontent.com/33215297/32229713-0f7519f4-be84-11e7-864d-ff915ad7f31a.png">

**Comment by tanminh** [comment]
Trong added list thì không có gì
<img width="960" alt="screenshot 2017-10-31 21 39 33" src="https://user-images.githubusercontent.com/33215297/32229752-28c8a484-be84-11e7-9e06-96d8ffabdc2c.png">

**Comment by tanminh** [comment]
Rồi lại hiện lại sau khi bấm refresh tiếp, như ma
<img width="960" alt="screenshot 2017-10-31 21 41 26" src="https://user-images.githubusercontent.com/33215297/32229813-4d79f90e-be84-11e7-96c6-56a6f1eed5af.png">

**Comment by tanminh** [comment]
Refresh nữa thì đứng im luôn
<img width="960" alt="screenshot 2017-10-31 21 44 01" src="https://user-images.githubusercontent.com/33215297/32229986-ab7b4120-be84-11e7-970b-277f21a67fd1.png">

**Comment by daltonnyx** [comment]
Đã fix
