### ISSUE TITLE
Khi chọn công cụ Pan trong chrome không hiện dấu bàn tay

### ISSUE THREAD

**Issue by tanminh** [daltonnyx/homeclick#3]
<img width="960" alt="screenshot 2017-10-30 13 42 31" src="https://user-images.githubusercontent.com/33215297/32157817-733afc68-bd78-11e7-8b0d-7df904d4fcf5.png">
# @

**Comment by daltonnyx** [comment]
open again

**Comment by daltonnyx** [comment]
Xong r anh nhé

**Comment by tanminh** [comment]
Ok
