### ISSUE TITLE
Hiển thị diện tích sai.

### ISSUE THREAD

**Issue by thuyanHB** [daltonnyx/homeclick#43]
![image](https://user-images.githubusercontent.com/33772438/33987444-784bf43e-e0f3-11e7-9d1b-69b86b0e44d8.png)

**Comment by daltonnyx** [comment]
![image](https://user-images.githubusercontent.com/14941648/34979028-b9d94b10-fad2-11e7-8344-9ac554b6915d.png)
Đã fix
