### ISSUE TITLE
Phần sàn nên có ô màu default kế bên ô màu chọn

### ISSUE THREAD

**Issue by tanminh** [daltonnyx/homeclick#8]
<img width="960" alt="screenshot 2017-10-30 14 04 27" src="https://user-images.githubusercontent.com/33215297/32158464-56c69f8a-bd7b-11e7-8f3a-bbd7fab92a5b.png">

**Comment by daltonnyx** [comment]
Cái này nút xoá là reset về default đó anh

**Comment by tanminh** [comment]
Ok
